language: php

php:
  - 5.5.9
  - 5.6
  - 7.0

before_install:
  - mv .env.example .env

install:
  - /home/travis/.phpenv/versions/5.5.9/bin/composer self-update
  - composer install

script:
  - php artisan key:generate
  - vendor/bin/phpunit
